#!/usr/bin/env bash
# configures a new Ubuntu machine to Install nginx on web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request using curl,
# it must return a page that contains the string Hello World!
sudo apt-get update
sudo apt-get -y install nginx

# Override default Nginx index file
sudo chown -R ubuntu /var/www/html
echo 'Hello World!' > /var/www/html/index.html

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    
    root   /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;
    
    location / {
        try_files $uri $uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

sudo service nginx restart
