#!/usr/bin/env bash
# configures a new Ubuntu machine to Install nginx on web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request using curl,
# it must return a page that contains the string Hello World!
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

# Create a backup of default Nginx index file
sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Override default Nginx index file
sudo chown -R ubuntu /var/www/html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

# Set the redirection route

sudo sed -i '/server_name _;/a \
\
        location /redirect_me {\
            return 301 http:\/\/www.youtube.com/watch?v=QH2-TGUlwu4;\
        }' /etc/nginx/sites-enabled/default

sudo service nginx start
