#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page
# that contains the string Ceci n'est pas une page
sudo apt-get update
sudo apt-get -y install nginx

# Override default Nginx index file
sudo chown -R ubuntu /var/www/html
echo 'Hello World!' > /var/www/html/index.html
echo 'Ceci n'est pas une page' > /var/www/html/404.html

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root   /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    
    error_page 404 /404.html;
}" | sudo tee /etc/nginx/sites-enabled/default > /dev/null

sudo service nginx restart
