#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom HTTP header X-Served-By
# its value is the hostname of the server Nginx is running on
sudo sed -i "/location \/ {/a \                add_header X-Served-By \$hostname;" /etc/nginx/sites-enabled/default
sudo service nginx restart
