#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom HTTP header X-Served-By
# its value is the hostname of the server Nginx is running on
sudo apt-get update
sudo apt-get -y install nginx

# Override default Nginx index file
sudo chown -R ubuntu /var/www/html
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root  /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    add_header X-Served-By $HOSTNAME;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
}" > /etc/nginx/sites-enabled/default

sudo service nginx restart
