#!/usr/bin/env bash
# displays To infinity and beyond indefinitely
# displays I am invincible!!! when receiving a SIGTERM signal

sig_handler(){
	echo "I am invincible!!!"
}
trap sig_handler SIGTERM

while ((1))
do
	echo "To infinity and beyond"
	sleep 2
done
