#!/usr/bin/env bash
# Comment
cp /etc/hosts ~/hosts.new
sed -i '/127.0.0.1/d' ~/hosts.new
sed -i '1i127.0.0.2 localhost' ~/hosts.new
sed -i '/facebook.com/d' ~/hosts.new
echo '8.8.8.8 facebook.com' >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
rm ~/hosts.new
