#!/usr/bin/env bash
# Fix a container so that Nginx is running as the nginx user
sudo chmod 644 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo pkill apache2
sudo sed -i "s/listen 80 default_server/listen 8080 default_server/" /etc/nginx/sites-enabled/default
sudo sed -i 's/listen \[::\]:80 default_server ipv6only=on;/listen \[::\]:8080 default_server ipv6only=on;/' /etc/nginx/sites-enabled/default
sudo -u nginx nginx
