#!/usr/bin/env bash
# Fix a container so that Nginx is running as the nginx user
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo pkill apache2
sudo -u nginx nginx
